### PR TITLE
PyCharm 3.1.1 Community Edition

### PR DESCRIPTION
**Pull request by cebik**

### CODE REVIEW

**Comment by pericazivkovic** [comment]
Thanks I'm testing this and also checking with PyCharm guys and girls is it allowed to re-distribute

**Comment by cebik** [comment]
Nice :D, Thx for info.

2014-04-02 21:25 GMT+02:00 Perica Zivkovic notifications@github.com:

**Comment by pericazivkovic** [comment]
I'm testing it and here is what I found:
- Pro's:
  - Unpacking and installation are going smooth. Great job on patching the config!
  - Icon looks great and basic functionality is there!
- Cons:
  - Huge package! Adds 120+MB on top of the PP distro. That doubles the size of our installer!
  - Debugger does not work, it bombs out with an error:

```
"C:\Users\p.zivkovic\Desktop\Portable Python 2.7.6.1\App\PyCharm\..\pythonw.exe" "C:\Users\p.zivkovic\Desktop\Portable Python 2.7.6.1\App\PyCharm\helpers\pydev\pydevd.py" --multiproc --client 127.0.0.1 --port 18125 --file C:/Users/p.zivkovic/Documents/GitHub/portablepython/2.7/test_imports.py
Traceback (most recent call last):
  File "C:\Users\p.zivkovic\Desktop\Portable Python 2.7.6.1\App\PyCharm\helpers\pydev\pydevd.py", line 2, in <module>
    from django_debug import DjangoLineBreakpoint
  File "C:\Users\p.zivkovic\Desktop\Portable Python 2.7.6.1\App\PyCharm\helpers\pydev\django_debug.py", line 3, in <module>
    from pydevd_comm import CMD_SET_BREAK
  File "C:\Users\p.zivkovic\Desktop\Portable Python 2.7.6.1\App\PyCharm\helpers\pydev\pydevd_comm.py", line 107, in <module>
    import pydevconsole
  File "C:\Users\p.zivkovic\Desktop\Portable Python 2.7.6.1\App\PyCharm\helpers\pydev\pydevconsole.py", line 21, in <module>
    import fix_getpass
ImportError: No module named fix_getpass

Process finished with exit code 1
```

even with this size I would think it is ok to include it but that debugger is a must have I think. 

I will test some more there is a new branch which I'm preparing for 2.7.6.1 release with your pull merged.

https://github.com/pericazivkovic/portablepython/tree/cebik-master

Comments, ideas?

**Comment by cebik** [comment]
Hi

I found the problem.
I fixed patch file (commit "FIX Fix directories path (weird path reference)")

**Comment by cebik** [comment]
Do you need another pull request? I have no idea about it :)
I've checked debuging with this example and now it's working
http://confluence.jetbrains.com/display/PYH/Debugger

I must create new 3.1.2 version so tell me before you accept this.
I'll try do this ASAP.

**Comment by pericazivkovic** [comment]
Fix for 2.7.x is enough if you have that as I will update 3.x later anyway

**Comment by cebik** [comment]
It's fix for 2.7 and 3.x (python)
I'll do new PYCharm Communuty Edition 3.1.2 later
7 kwi 2014 15:13 "Perica Zivkovic" notifications@github.com napisał(a):

**Comment by pericazivkovic** [comment]
Great, thank you. Is it possible to disable update check? After a while new version will be available and it will prompt user to update. Automatic update process can mess-up portable version you prepared.

**Comment by cebik** [comment]
I dont know. I will check it tomorrow. And I try make new version.
7 kwi 2014 21:03 "Perica Zivkovic" notifications@github.com napisał(a):

**Comment by cebik** [comment]
I've created patch for CE 3.1.2 but there is problem with updating skeletons. Autocomplete working good only after re-adding Python interpreter in settings. I'll try to fix it.

**Comment by pericazivkovic** [comment]
Nice to have 3.1.2! I have prepared 2.7.6.1 release - this would be great addition to it!

**Comment by cebik** [comment]
There's problem in PYCharm 312 version :(
PYCharm doesn't correctly updating skeletons so intelisense don't working
good. User must remove and add python interpreter by him self.
But I don't giving up..
If I don't do it by my self I'll write to PYCharm author.
8 kwi 2014 22:41 "Perica Zivkovic" notifications@github.com napisał(a):

**Comment by pericazivkovic** [comment]
we can also stick with 3.1.1 if we can disable auto update notification. 3.1.2 will anyway be obsolete in couple of months when they do yet another update. Or does it contain some must-have features that are not in 3.1.1?

**Comment by cebik** [comment]
I did it yesterday. Auto update is disabled. Changes are committed.
9 kwi 2014 06:06 "Perica Zivkovic" notifications@github.com napisał(a):

**Comment by cebik** [comment]
Wait..
It looks like when other.xml (don't update settings ) is added then code
autocomplete doesn't working (doesn't auto refresh skeletons) on start in
version 3.1.1 and 3.1.2
:(

2014-04-09 7:45 GMT+02:00 Krzysztof Cebulski kcebulski@gmail.com:

**Comment by cebik** [comment]
I did it :D everything working good in 3.1.1 and 3.1.2 PyCharm version.
I've tested debuging and code auto completion.
Auto update is disabled.

https://github.com/cebik/portablepython/commits/master

Best regards

2014-04-09 9:03 GMT+02:00 Krzysztof Cebulski kcebulski@gmail.com:

**Comment by pericazivkovic** [comment]
Awesome! I will test this weekend and hope to be able to complete 2.7.6.1 release with this addition. Will let you know how it goes.

**Comment by cebik** [comment]
Nice, thx
12 kwi 2014 07:45 "Perica Zivkovic" notifications@github.com napisał(a):

**Comment by pericazivkovic** [comment]
Done. It is in master now, thank you!

**Comment by cebik** [comment]
Nice. Thank you also.
13 kwi 2014 17:08 "Perica Zivkovic" notifications@github.com napisał(a):

**Comment by Metallicow** [comment]
My Gosh! The performance on a usb2 is crap(XP Pro SP4, PyCharm 3.1.2 BTW).
I recall installing the desktop version of PyCharm at one time to check it out and it definitely wasn't dirt slow with intermediate consistent lagging. geez... If SourceCoder was like that, I would slap myself _more than twice_. Not even Editra is like that and it is written in pure-python also. 

Anyhow, after the initial indexing(It took about 20min) I created a portable project so I can help out with this project more.
In a nutshell I created a project on my 64GB thumbdrive which houses all my other portable apps, and consistently the GUI starts lagging, especially after switching to my browser and then back. This is probably a setting or something I would think needs tweaked and patched. It seems most all IDEs are guilty of running about a million processes all the time, when they are not needed. I know part of the culprit is all those tooltip popups and whatnot.

I noticed there is some patching done. maybe another patch is what is needed...
@cebik @pericazivkovic Any ideas? ...maybe PyCharm's unoptimized community code, or other(certain settings, etc...)?
The lag problem is bad enough it should require an issue if not a simple fix, if fixable.

EDIT: Python crashed on second round, but didn't kill PyCharm. This was a background process...?

```
Failed modules
Portable Python 2.7 
_imagingft
dde
pygame._numericsndarray
pygame._numericsurfarray
wx._propgrid
Generation of skeletons for the modules above will be tried again when the modules are updated or a new version of generator is available.
```

EDIT2: I think it might be PyCharm. See this. http://youtrack.jetbrains.com/issue/WEB-12179

**Comment by Metallicow** [comment]
I checked out the "next" version for desktop and it doesn't seem to have the performance/freeze/lag problem.

...So it looks like the best course of action for this is to wait until their new 3.4 goes live, patch the thing for portability and try it again.

**Pull request merged**
